### ISSUE TITLE
Can't connect to a new wifi network

### ISSUE THREAD

**Issue by tanay1337** [quantumvoid0/better-control#56]
Hey team, today I tried connecting to a wifi network with the app and it did not work. I tried three times and here's the log for that interaction:

```
❯ control -l0
02:27:955 [INFO]: No previous sink saved.
02:28:027 [INFO]: Initializing application
02:28:027 [INFO]: Settings loaded
02:28:031 [INFO]: Starting asynchronous tab creation
02:28:038 [INFO]: Settings button created and attached to notebook
ok
02:28:117 [INFO]: Updating audio device lists...
02:28:136 [INFO]: Current active output sink: alsa_output.pci-0000_c1_00.6.analog-stereo
02:28:153 [INFO]: Adding output sink: alsa_output.pci-0000_c1_00.6.analog-stereo (Family 17h/19h/1ah HD Audio Controller Analog Stereo)
02:28:210 [INFO]: Current active input source: alsa_input.pci-0000_c1_00.6.analog-stereo
02:28:229 [INFO]: Adding input source: alsa_input.pci-0000_c1_00.6.analog-stereo (Family 17h/19h/1ah HD Audio Controller Analog Stereo)
02:28:296 [DEBUG]: Parsing Line:
02:28:296 [DEBUG]: Parsed Applications: []
02:28:313 [DEBUG]: Parsing source output line:
02:28:314 [DEBUG]: Parsed Source Outputs: []
02:28:397 [DEBUG]: Parsing Line:
02:28:397 [DEBUG]: Parsed Applications: []
02:28:398 [INFO]: Starting periodic (500ms) audio refresh
02:28:398 [INFO]: Started periodic (500ms) audio monitoring
02:28:400 [INFO]: Created Volume tab
02:28:409 [INFO]: Initializing WiFi tab
02:28:496 [INFO]: Created Wi-Fi tab
02:28:548 [INFO]: Created Bluetooth tab
02:28:896 [INFO]: Created Battery tab
02:28:949 [INFO]: Created Display tab
02:28:949 [INFO]: All tabs created, finalizing UI
02:28:950 [INFO]: Loading WiFi networks after tabs initialization
02:29:008 [INFO]: Found 2 WiFi networks
02:29:041 [DEBUG]: Parsing Line:
02:29:041 [DEBUG]: Parsed Applications: []
02:29:460 [INFO]: Updating audio device lists...
02:29:476 [INFO]: Current active output sink: alsa_output.pci-0000_c1_00.6.analog-stereo
02:29:494 [INFO]: Adding output sink: alsa_output.pci-0000_c1_00.6.analog-stereo (Family 17h/19h/1ah HD Audio Controller Analog Stereo)
02:29:538 [INFO]: Current active input source: alsa_input.pci-0000_c1_00.6.analog-stereo
02:29:550 [INFO]: Adding input source: alsa_input.pci-0000_c1_00.6.analog-stereo (Family 17h/19h/1ah HD Audio Controller Analog Stereo)
02:29:578 [DEBUG]: Parsing Line:
02:29:578 [DEBUG]: Parsed Applications: []
02:30:471 [DEBUG]: Parsing source output line:
02:30:471 [DEBUG]: Parsed Source Outputs: []
02:31:472 [DEBUG]: Parsing Line:
02:31:473 [DEBUG]: Parsed Applications: []
02:35:686 [INFO]: Connecting to WiFi network: Premier Inn Free
Error: unknown connection 'Premier Inn Free'.
02:35:800 [INFO]: Refreshing WiFi networks list
02:35:864 [INFO]: Found 2 WiFi networks
02:42:122 [INFO]: Connecting to WiFi network: Premier Inn Free
Error: unknown connection 'Premier Inn Free'.
02:42:208 [INFO]: Refreshing WiFi networks list
02:42:282 [INFO]: Found 3 WiFi networks
02:48:374 [INFO]: Connecting to WiFi network: Premier Inn Free
Error: unknown connection 'Premier Inn Free'.
02:48:477 [INFO]: Refreshing WiFi networks list
02:48:544 [INFO]: Found 3 WiFi networks
02:50:656 [INFO]: Application quitted
```

The connection works at first try when using nmcli:

```
❯ nmcli d wifi connect "Premier Inn Free"
Device 'wlan0' successfully activated with '4d5d8ed8-738b-486d-acad-a1faf735d295'.
```

**Comment by fcsm1922** [comment]
Today I noticed that the wi-fi network does not automatically switch to a stronger signal..which I used to connect to....with

**Comment by RQuarx** [comment]
Is it because of python string stuff? I also got this problem a few while ago, but don't what the hell happened, nor how to fix it. Based on the logs, it seems like nmcli cant find the ssid, which might be happening because: weird string behaviour by python, different encoding, or just some processing messing up the logic...

**Comment by FelipeFMA** [comment]
Weird, I've connected to many networks, and this has never happened to me. I wouldn't even know where to start debugging

**Comment by FelipeFMA** [comment]
I created a network with the same name 'Premier Inn Free' and it won't connect

**Comment by FelipeFMA** [comment]
I'm already half done fixing it

**Comment by FelipeFMA** [comment]
FIXED

**Comment by tanay1337** [comment]
Hello, this still isn't solved for me. I can't test with the previous free wifi, as I am not in that location anymore, but I tried with two protected networks and here are the relevant log partials:

```
22:23:931 [INFO]: Connecting to WiFi network: Tanay’s iPhone
Error: Connection activation failed: No suitable device found for this connection (device wlan0 not available because profile is not compatible with device (mismatching interface name)).
Passwords or encryption keys are required to access the wireless network 'Tanay’s iPhone'.
Warning: password for '802-11-wireless-security.psk' not given in 'passwd-file' and nmcli cannot ask without '--ask' option.
Error: Connection activation failed: Secrets were required, but not provided.
Error: Connection activation failed: No suitable device found for this connection (device wlan0 not available because profile is not compatible with device (mismatching interface name)).
Error: 802-11-wireless-security.key-mgmt: property is missing.
22:53:124 [INFO]: Refreshing WiFi networks list
22:53:237 [INFO]: Found 14 WiFi networks
22:57:730 [INFO]: Connecting to WiFi network: WLAN-769228
Passwords or encryption keys are required to access the wireless network 'WLAN-769228'.
Warning: password for '802-11-wireless-security.psk' not given in 'passwd-file' and nmcli cannot ask without '--ask' option.
Error: Connection activation failed: Secrets were required, but not provided
Hint: use 'journalctl -xe NM_CONNECTION=eadc439a-436f-4aa5-9383-83bbcd9361df + NM_DEVICE=wlan0' to get more details.
Passwords or encryption keys are required to access the wireless network 'WLAN-769228'.
Warning: password for '802-11-wireless-security.psk' not given in 'passwd-file' and nmcli cannot ask without '--ask' option.
Error: Connection activation failed: Secrets were required, but not provided.
Passwords or encryption keys are required to access the wireless network 'WLAN-769228'.
Warning: password for '802-11-wireless-security.psk' not given in 'passwd-file' and nmcli cannot ask without '--ask' option.
Error: Connection activation failed: Secrets were required, but not provided
Hint: use 'journalctl -xe NM_CONNECTION=eadc439a-436f-4aa5-9383-83bbcd9361df + NM_DEVICE=wlan0' to get more details.
Error: 802-11-wireless-security.key-mgmt: property is missing.
23:24:167 [INFO]: Refreshing WiFi networks list
```

Again, connecting directly with nmcli with --ask works just fine.

**Comment by FelipeFMA** [comment]
Oh, maybe I know why it happened, I think I to forgot to make it use other interface names :P

**Comment by FelipeFMA** [comment]
fixed again, can you check if it works for you now?

**Comment by tanay1337** [comment]
Works like a charm now, thanks! Marking it as resolved.
