### ISSUE TITLE
Display rotation - resolution and mouse

### ISSUE THREAD

**Issue by tanay1337** [quantumvoid0/better-control#99]
**Describe the bug**
- I am running Hyprland with `1.566667` scaling. Upon using the rotate option, it does rotate my screen up messes up the scaling.
- The mouse movement/direction does not work as expected on a rotated screen making it hard to revert back.

**To Reproduce**
1. Go to 'Display'
2. Click on any rotate button (you probably need some scaling option other than 1/default)
3. Your scaling should now be messed up.
4. Mouse movement should be weird making it hard to revert.

**Expected behavior**
- Rotation respects scaling (also when reverting back).
- Usable mouse movements.
- Option to hide this setting to not click this by mistake.

**Comment by tanay1337** [comment]
A potential helpful feature in addition - if the confirmation to apply isn't clicked in 10 second, revert it back. Would have helped me a lot when i got stuck.

**Comment by Sandesh2007** [comment]
i am looking into that, will be fixed soon.

**Comment by Sandesh2007** [comment]
@tanay1337  i have fixed the scaling issue but i don't think so we could have the mouse working in as normal in other rotation!

**Comment by tanay1337** [comment]
Thanks a lot @Sandesh2007, the revert back feature is very appreciated. Understood on the mouse, I think I misunderstood something.

I think there's still some bugs with this feature and it should be considered as a optional feature that can be hidden cc: @quantumvoid0 @Sandesh2007 

A few examples:
- There's two icons that look exactly the same. One has to hover over the buttons to understand what the labels do.
- Here's what my screen looks like after it is reverted (see screenshot). Using `swww restore` does not work and I have to switch the wallpapers twice to get it back to normal.
- The left button rotates the screen to the right and vice-versa. 
- Also the icons imply for me that if I keep pressing the rotate button, it will rotate 90 degrees more.

![Image](https://github.com/user-attachments/assets/386bffe8-63be-4a7e-a2a9-0e3894a41479)

**Comment by quantumvoid0** [comment]
@tanay1337 can u see if its fixed now as @Sandesh2007 had made some changes at #103

**Comment by tanay1337** [comment]
I didn't get the chance to do comprehensive testing as the app keeps crashing on me (and testing this messes up my wallpaper everytime), but immediately noticed a few things:
- I pressed "Rotate counter-clockwise" and it rotated the screen clockwise for me.
- 90 degrees right rotates the screen to 90 degress left.
- Flip vertical causes a weird effect.
- The wallpaper mess up still happens.

A few suggestions:
- Moving the Orientation section to the bottom of the tab as brightness and blue light might be more widely used options.
- Removing the feature to a separate branch as it's quite buggy in it's current state and moving it to main after more testing.

**Comment by tanay1337** [comment]
Thanks @Sandesh2007, the clockwise and anti-clockwise buttons work fine, but all the other issues still persist for me.

**Comment by Sandesh2007** [comment]
This feature seems to do not work as intended and have been removed for now
